# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ncalc.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"0\n\x10SessionOperation\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x32\xfd\x01\n\nCalculator\x12&\n\x06\x43reate\x12\x07.Number\x1a\x11.SessionOperation\"\x00\x12&\n\x06\x41nswer\x12\x11.SessionOperation\x1a\x07.Number\"\x00\x12#\n\x03\x41\x64\x64\x12\x11.SessionOperation\x1a\x07.Number\"\x00\x12(\n\x08Subtract\x12\x11.SessionOperation\x1a\x07.Number\"\x00\x12(\n\x08Multiply\x12\x11.SessionOperation\x1a\x07.Number\"\x00\x12&\n\x06\x44ivide\x12\x11.SessionOperation\x1a\x07.Number\"\x00\x62\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=37,
)


_SESSIONOPERATION = _descriptor.Descriptor(
  name='SessionOperation',
  full_name='SessionOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='SessionOperation.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SessionOperation.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['SessionOperation'] = _SESSIONOPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'calc_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)

SessionOperation = _reflection.GeneratedProtocolMessageType('SessionOperation', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONOPERATION,
  '__module__' : 'calc_pb2'
  # @@protoc_insertion_point(class_scope:SessionOperation)
  })
_sym_db.RegisterMessage(SessionOperation)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=343,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='Calculator.Create',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_SESSIONOPERATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Answer',
    full_name='Calculator.Answer',
    index=1,
    containing_service=None,
    input_type=_SESSIONOPERATION,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Calculator.Add',
    index=2,
    containing_service=None,
    input_type=_SESSIONOPERATION,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subtract',
    full_name='Calculator.Subtract',
    index=3,
    containing_service=None,
    input_type=_SESSIONOPERATION,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Multiply',
    full_name='Calculator.Multiply',
    index=4,
    containing_service=None,
    input_type=_SESSIONOPERATION,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Divide',
    full_name='Calculator.Divide',
    index=5,
    containing_service=None,
    input_type=_SESSIONOPERATION,
    output_type=_NUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
